use_dwpose: true
# pretrained_model_path: "runwayml/stable-diffusion-v1-5"
pretrained_model_path: '/huggingface00/hub/models--runwayml--stable-diffusion-v1-5/snapshots/1d0c4ebf6ff58a5caecab40fa1406526bca4b5b9'
pretrained_vae_path: "/models00/pretrained_models/sd-vae-ft-mse"
pretrained_appearance_encoder_path: "/models00/pretrained_models/MagicAnimate/appearance_encoder"
pretrained_controlnet_path: "/models00/pretrained_models/MagicAnimate/densepose_controlnet"
pretrained_unet_path: ""
image_encoder_path: ""

appearance_controlnet_motion_checkpoint_path: "/work00/magic_animate_unofficial/outputs/train_stage1_wo_imageencoder_celebv_3machine_2accumulation-2023-12-26T14-07-38/checkpoints/checkpoint-steps8000.ckpt"
# 如果指定motion_module，appearance_controlnet_motion_checkpoint_path中的motion会被覆盖
motion_module: "/models00/pretrained_models/MagicAnimate/temporal_attention/temporal_attention.ckpt"

savename: null

fusion_blocks: "midup"

seed:           [1]
steps:          25
guidance_scale: 4.0

source_image:
    # - "/work00/magic_animate_unofficial/data/mj_girls/cat3.jpg"
    # - "/work00/magic_animate_unofficial/data/mj_girls/cat2.jpg"
    # - "/work00/magic_animate_unofficial/data/mj_girls/cat.jpeg"
    - "/work00/magic_animate_unofficial/data/mj_girls/ag1.jpeg"
    - "/work00/magic_animate_unofficial/data/mj_girls/ag1.jpeg"

    - "/work00/magic_animate_unofficial/data/celebv/10876-2-7eMjYXRcm-0_12_0.mp4"
    - "/work00/magic_animate_unofficial/data/celebv/10894-8-7ebsTST4bSw_1_0.mp4"
    - "/work00/magic_animate_unofficial/data/movies/Scent_of_a_Woman_Alfredo_Pacino000350_2.mp4"

video_path:
    - "/work00/magic_animate_unofficial/data/celebv/10876-2-7eMjYXRcm-0_12_0.mp4"
    - "/work00/magic_animate_unofficial/data/celebv/10894-8-7ebsTST4bSw_1_0.mp4"

    - "/work00/magic_animate_unofficial/data/celebv/10876-2-7eMjYXRcm-0_12_0.mp4"
    - "/work00/magic_animate_unofficial/data/celebv/10894-8-7ebsTST4bSw_1_0.mp4"
    - "/work00/magic_animate_unofficial/data/movies/Scent_of_a_Woman_Alfredo_Pacino000350_2.mp4"

context:
  context_frames: 16
  context_stride: 1
  context_overlap: 0

inference_config: "configs/inference/magic_inference.yaml"
size: [512, 512]
L:    16
S:    1
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: false

unet_additional_kwargs:
  unet_use_cross_frame_attention: false
  unet_use_temporal_attention: false
  use_motion_module: false
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: false
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
    - Temporal_Self
    - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 24
    temporal_attention_dim_div: 1
  # Addition for image embeddings
  use_image_condition            : false

noise_scheduler_kwargs:
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
