# pretrained_model_path: "runwayml/stable-diffusion-v1-5"
pretrained_model_path: '/huggingface00/hub/models--runwayml--stable-diffusion-v1-5/snapshots/1d0c4ebf6ff58a5caecab40fa1406526bca4b5b9'
pretrained_vae_path: "/models00/pretrained_models/sd-vae-ft-mse"
pretrained_appearance_encoder_path: "/models00/pretrained_models/MagicAnimate/appearance_encoder"
pretrained_controlnet_path: "/models00/pretrained_models/MagicAnimate/densepose_controlnet"

pretrained_unet_path: ""

motion_module: "/models00/pretrained_models/MagicAnimate/temporal_attention/temporal_attention.ckpt"
image_encoder_path: "/work00/IP-Adapter/IP-Adapter/models/image_encoder"

use_dwpose: false

savename: null

fusion_blocks: "midup"

seed:           [1]
steps:          25
guidance_scale: 7.5

source_image:
  # - "/work00/magic_animate_unofficial/data/fashion_dataset/91aHjkHkSQS.mp4"
  # - "/work00/magic_animate_unofficial/data/fashion_dataset/91gJasnQEyS.mp4"
  - "/work00/magic-animate/inputs/applications/source_image/monalisa.png"
  - "/work00/magic-animate/inputs/applications/source_image/0002.png"
  - "/work00/magic-animate/inputs/applications/source_image/demo4.png"
  - "/work00/magic-animate/inputs/applications/source_image/dalle2.jpeg"
  - "/work00/magic-animate/inputs/applications/source_image/dalle8.jpeg"
  - "/work00/magic-animate/inputs/applications/source_image/multi1_source.png"
video_path:
  # - "/work00/magic-animate/inputs/applications/driving/densepose/running.mp4"
  # - "/work00/magic-animate/inputs/applications/driving/densepose/dancing2.mp4"
  - "/work00/magic-animate/inputs/applications/driving/densepose/running.mp4"
  - "/work00/magic-animate/inputs/applications/driving/densepose/demo4.mp4"
  - "/work00/magic-animate/inputs/applications/driving/densepose/demo4.mp4"
  - "/work00/magic-animate/inputs/applications/driving/densepose/running2.mp4"
  - "/work00/magic-animate/inputs/applications/driving/densepose/dancing2.mp4"
  - "/work00/magic-animate/inputs/applications/driving/densepose/multi_dancing.mp4"

inference_config: "configs/inference/magic_inference.yaml"
# size: [512, 512]
size: [768, 512]
L:    16
S:    1
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: false
