source_image:
  - "/root/code/yangshurong/VividVideoGeneration_dit/new_test_data/001.gif"
  - "/root/code/yangshurong/VividVideoGeneration_dit/new_test_data/002.gif"
  - "/root/code/yangshurong/VividVideoGeneration_dit/new_test_data/003.gif"
  - "/root/code/yangshurong/VividVideoGeneration_dit/new_test_data/004.gif"
  - "/root/code/yangshurong/VividVideoGeneration_dit/new_test_data/005.gif"
  - "/root/code/yangshurong/VividVideoGeneration_dit/new_test_data/006.gif"
  - "/root/code/yangshurong/VividVideoGeneration_dit/new_test_data/007.gif"
