control_aux_type: "fromfile"

controlnet_type: '3d'
controlnet_config: 'configs/inference/sparse_control.yaml'

# chose densepose, segface, dwpose, fromfile
# pretrained_model_path: "runwayml/stable-diffusion-v1-5"
pretrained_model_path: "/root/.cache/yangshurong/StableDiffusion"
pretrained_vae_path: "/root/.cache/yangshurong/magic_pretrain/sd-vae-ft-mse"
pretrained_controlnet_path: "/root/.cache/yangshurong/magic_pretrain/MagicAnimate/densepose_controlnet"
pretrained_appearance_encoder_path: "/root/.cache/yangshurong/magic_pretrain/MagicAnimate/appearance_encoder"
pretrained_unet_path: ""
image_encoder_path: ""

# motion_module: ""
motion_module: "/root/.cache/yangshurong/magic_pretrain/MagicAnimate/temporal_attention/temporal_attention.ckpt"

# appearance_controlnet_motion_checkpoint_path: "/data/work/animate_based_ap_ctrl/outputs/train_stage2_w_imageencoder_celebv-2023-12-30T14-15-31/checkpoints/checkpoint-steps4000.ckpt"
# 如果指定motion_module，appearance_controlnet_motion_checkpoint_path中的motion会被覆盖
# motion_module: "/data/models/pretrained_models/MagicAnimate/temporal_attention/temporal_attention.ckpt"

savename: null

fusion_blocks: "midup"

seed:           [1]
steps:          25
guidance_scale: 7.5

context:
  context_frames: 16
  context_stride: 1
  context_overlap: 0

source_image:
  - "/root/code/yangshurong/magic-animate/inputs/applications/source_image/monalisa.png"
  - "/root/code/yangshurong/magic-animate/inputs/applications/source_image/demo4.png"
  - "/root/code/yangshurong/VividVideoGeneration/me_test_data/my_data_refer16.gif"
  - "/root/code/yangshurong/VividVideoGeneration/me_test_data/my_data_refer1.gif"
  - "/root/code/yangshurong/VividVideoGeneration/me_test_data/my_data_refer20.gif"


video_path:
  - "/root/code/yangshurong/magic-animate/inputs/applications/driving/densepose/running.mp4"
  - "/root/code/yangshurong/magic-animate/inputs/applications/driving/densepose/demo4.mp4"
  - "/root/code/yangshurong/VividVideoGeneration/me_test_data/my_data_control16.gif"
  - "/root/code/yangshurong/VividVideoGeneration/me_test_data/my_data_control1.gif"
  - "/root/code/yangshurong/VividVideoGeneration/me_test_data/my_data_control20.gif"

inference_config: "configs/inference/magic_inference.yaml"
size: [512, 512]
# 长度一致
L:    16
S:    1
I:    0
clip: 0
offset: 0
max_length: null
video_type: "condition"
invert_video: false
save_individual_videos: true

unet_additional_kwargs:
  unet_use_cross_frame_attention: false
  unet_use_temporal_attention: false
  use_motion_module: true
  motion_module_resolutions:
  - 1
  - 2
  - 4
  - 8
  motion_module_mid_block: false
  motion_module_decoder_only: false
  motion_module_type: Vanilla
  motion_module_kwargs:
    num_attention_heads: 8
    num_transformer_block: 1
    attention_block_types:
    - Temporal_Self
    - Temporal_Self
    temporal_position_encoding: true
    temporal_position_encoding_max_len: 24
    temporal_attention_dim_div: 1
  # Addition for image embeddings
  use_image_condition            : true

noise_scheduler_kwargs:
  beta_start: 0.00085
  beta_end: 0.012
  beta_schedule: "linear"
